name: C++ CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Cache Tools
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/clang
          ~/.cache/cmake
        key: tools-clang-18-stdlib-msan
        restore-keys: |
          tools-clang-18-stdlib
          tools-clang-18
          
    - name: Add LLVM Repository
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main"
        sudo apt-get update
        
    - name: Install Dependencies
      run: |
        sudo apt-get install -y \
          cmake \
          clang-18 \
          libc++-18-dev \
          libc++abi-18-dev \
          lld-18
        
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_CXX_COMPILER=clang++-18 \
          -DCMAKE_CXX_FLAGS="-stdlib=libc++ -fsanitize=memory -fno-omit-frame-pointer"
          
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug
      
    - name: Runtime Checks
      run: |
        cd ${{github.workspace}}/.github/actions/runtime-checks
        chmod +x ./run-checks.sh
        ./run-checks.sh
        
    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C Debug --output-on-failure
      
    - name: Create Release
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{github.workspace}}/build/your-executable-name
        tag_name: v${{ github.run_number }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
